name: Autogen Lua docs json

on:
	workflow_dispatch:
	push:
		branches: [ android-dev ]

jobs:
    autogen:
        if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[gen]') }}
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                sudo apt update
                sudo apt install -y python3 zip

            - name: Autogen
              run: python3 ./autogen/convert_functions.py
                #python3 ./autogen/convert_constants.py
                #python3 ./autogen/convert_functions.py

            - name: Zip files
              run: |
                cd ./autogen/converted
                zip autogen_converted.zip *.json

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: autogen-files
                path: ./autogen/converted/autogen_converted.zip